name = "Pajarito"
uuid = "2f354839-79df-5901-9f0a-cdb2aac6fe30"
authors = ["Chris Coey, Miles Lubin, Juan Pablo Vielma"]
repo = "https://github.com/JuliaOpt/Pajarito.jl.git"
version = "0.6.2"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
ConicBenchmarkUtilities = "e95a7839-07fb-532d-9a0e-071766bb5168"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathProgBase = "fdba3010-5040-5b88-9595-932c9decdf73"

[compat]
Compat = "~1.0, ~2.0"
ConicBenchmarkUtilities = "~0.3.1"
ECOS = "≥ 0.9.1"
GLPKMathProgInterface = "≥ 0.4.0"
JuMP = "~0.15, ~0.16, ~0.17, ~0.18"
MathProgBase = "~0.5, ~0.6, ~0.7"
SCS = "≥ 0.4.0"
julia = "1"

[extras]
ECOS = "e2685f51-7e38-5353-a97d-a921fd2c8199"
GLPKMathProgInterface = "3c7084bd-78ad-589a-b5bb-dbd673274bea"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"

[targets]
test = ["GLPKMathProgInterface", "SCS", "ECOS", "Logging"]
